"""re added nullable in user_order table

Revision ID: 27a295f37ac9
Revises: 83f996c36a0f
Create Date: 2021-01-03 18:39:02.604397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27a295f37ac9'
down_revision = '83f996c36a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_order', 'date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_order', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_order', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user_order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_order', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_order', 'date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
