"""added test

Revision ID: 2d9664274efb
Revises: 83e82a79a98c
Create Date: 2021-01-03 18:24:22.128117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9664274efb'
down_revision = '83e82a79a98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'test')
    # ### end Alembic commands ###
