"""empty message

Revision ID: 328875683bf7
Revises: be0f415d0aa7
Create Date: 2021-01-04 02:39:47.847359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328875683bf7'
down_revision = 'be0f415d0aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_constraint('user_order_menu_id_fkey', 'user_order', type_='foreignkey')
    op.drop_column('user_order', 'menu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_order_menu_id_fkey', 'user_order', 'menu', ['menu_id'], ['id'])
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('main_menu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drink_menu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drink_menu'], ['drink_menu.id'], name='menu_drink_menu_fkey'),
    sa.ForeignKeyConstraint(['main_menu'], ['main_menu.id'], name='menu_main_menu_fkey'),
    sa.PrimaryKeyConstraint('id', name='menu_pkey')
    )
    # ### end Alembic commands ###
