"""removed price from menu

Revision ID: 35d5f930618f
Revises: 8f8755c27922
Create Date: 2021-01-03 20:35:25.039060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d5f930618f'
down_revision = '8f8755c27922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_menu', sa.Column('portion', sa.Enum('small', 'medium', 'large', name='portion_status_enum'), nullable=True))
    op.drop_column('menu', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('main_menu', 'portion')
    # ### end Alembic commands ###
