"""transfered columns to main_menu from menu

Revision ID: 7f99573b2fc0
Revises: 35d5f930618f
Create Date: 2021-01-03 20:49:09.428325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f99573b2fc0'
down_revision = '35d5f930618f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('main_menu', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu', 'main_menu', ['main_menu'], ['id'])
    op.drop_column('menu', 'vegetarian')
    op.drop_column('menu', 'portion')
    op.drop_column('menu', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('portion', postgresql.ENUM('small', 'medium', 'large', name='portion_status_enum'), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('vegetarian', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'main_menu')
    # ### end Alembic commands ###
