"""added drinks and menu table

Revision ID: 9f750c7e89ad
Revises: 7f99573b2fc0
Create Date: 2021-01-03 21:05:31.871268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f750c7e89ad'
down_revision = '7f99573b2fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('ice', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('main_menu', 'portion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_menu', sa.Column('portion', postgresql.ENUM('small', 'medium', 'large', name='portion_status_enum'), autoincrement=False, nullable=True))
    op.drop_table('drink_menu')
    # ### end Alembic commands ###
