"""added relations to drinks table

Revision ID: eb1564363dfd
Revises: 9f750c7e89ad
Create Date: 2021-01-03 21:07:09.891799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1564363dfd'
down_revision = '9f750c7e89ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('drink_menu', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu', 'drink_menu', ['drink_menu'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'drink_menu')
    # ### end Alembic commands ###
